#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements.
# * localhost resolves to 127.0.0.2
# * facebook.com resolves to 8.8.8.8.
# * The checker is running on Docker, so make sure to read this

cp /etc/hosts ~/hosts.new
sed -i s/^127.*localhost$/127.0.0.2\ localhost/ ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
